project_id = "uljwbfczrzbylizwagpe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-contact-email]
verify_jwt = true